version: '3.8'

services:
  node_backend:
    container_name: emp_api
    image: emp_api:0.0.1
    build: .
    # restart: always
    networks:
      - employeeAPI
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
      # - hostPath:containerPath:ro
    depends_on:
      - node_db
    env_file:
      - .env

  node_db:
    container_name: emp_db
    image: "postgres:14"
    ports:
     - ${DB_PORT}:${DB_PORT}
    networks:
      - employeeAPI
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=postgres
    volumes:
      - emp_data:/data/db

volumes:
  emp_data: {}

networks:
  employeeAPI: {}